name: Preview

permissions:
  contents: read

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXT_TELEMETRY_DISABLED: 1

on:
  pull_request:

jobs:
  preview:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch blog and news content
        run: |
          rm -rf content/blog content/news
          mkdir -p content/blog content/news
          curl -L https://github.com/HITSZ-OpenAuto/hoa-blog/tarball/main | tar -xz -C content/blog --strip-components=2
          curl -L https://github.com/HITSZ-OpenAuto/hoa-news/tarball/main | tar -xz -C content/news --strip-components=2

      - name: Fetch repositories in the organization
        run: curl -o repos_list.txt https://raw.githubusercontent.com/HITSZ-OpenAuto/repos-management/refs/heads/main/repos_list.txt

      - name: Clone hoa-major-data
        run: git clone https://github.com/HITSZ-OpenAuto/hoa-major-data

      - name: Download and Setup hoa-backend
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo HITSZ-OpenAuto/hoa-backend --pattern "hoa-backend-linux.tar.gz"
          tar -xzf hoa-backend-linux.tar.gz
          chmod +x hoa-backend
          sudo mv hoa-backend /usr/local/bin/

          rm hoa-backend-linux.tar.gz

      - name: Build course pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          hoa-backend --fetch

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Check format
        run: pnpm run fmt:check

      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest

      - name: Pull Vercel Environment Information
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts (no Vercel token)
        if: ${{ env.VERCEL_TOKEN == '' }}
        run: pnpm run build

      - name: Deploy Preview to Vercel
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} --archive=tgz
